export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_SEARCH_FILTER = "PRODUCT_SEARCH_FILTER";
